project_name: bbeth
release:
  draft: false

builds:
  -
    binary: bbeth
    dir: go/bbeth
    main: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.Date={{.CommitDate}}
      - -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
