FROM golang:1.15-buster as go-builder

ENV GOBIN=/go/bin

WORKDIR go/loadtool
COPY go/loadtool/go.mod go/loadtool/go.sum ./
RUN go mod download
COPY go/loadtool/cmd cmd
COPY go/loadtool/loader loader
COPY go/loadtool/*.go .
RUN find . && go build -o ${GOBIN}/loadtool main.go

FROM gcr.io/distroless/base
ENV PATH /usr/local/bin:${PATH}
COPY --from=go-builder /go/bin/loadtool /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/loadtool" ]
