FROM golang:1.15-buster as go-builder

ENV GOBIN=/go/bin

WORKDIR go/bbeth
COPY go/bbeth/go.mod go/bbeth/go.sum ./
RUN go mod download
COPY go/bbeth/cmd cmd
COPY go/bbeth/client client
COPY go/bbeth/collect collect
COPY go/bbeth/load load
COPY go/bbeth/root root
COPY go/bbeth/*.go .
RUN find . && go build -o ${GOBIN}/bbeth main.go

# FROM gcr.io/distroless/base
FROM debian:bullseye-slim
ENV PATH /usr/local/bin:${PATH}
COPY --from=go-builder /go/bin/bbeth /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/bbeth" ]
