FROM golang:1.15-buster as go-builder

ENV GOBIN=/go/bin

WORKDIR go/bbencheth
COPY go/bbencheth/go.mod go/bbencheth/go.sum ./
RUN go mod download
COPY go/bbencheth/cmd cmd
COPY go/bbencheth/client client
COPY go/bbencheth/collect collect
COPY go/bbencheth/load load
COPY go/bbencheth/root root
COPY go/bbencheth/*.go .
RUN find . && go build -o ${GOBIN}/bbencheth main.go

# FROM gcr.io/distroless/base
FROM debian:bullseye-slim
ENV PATH /usr/local/bin:${PATH}
COPY --from=go-builder /go/bin/bbencheth /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/bbencheth" ]
