apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest
spec:
  backoffLimit: 8
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadtest
        app.kubernetes.io/part-of: ethnet
    spec:
      restartPolicy: Never
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: bbeth-target-nodes-cfg
                  items:
                    # the static-nodes.json in the base is intentionaly empty.
                    - key: static-nodes.json
                      path: static-nodes.json
              - configMap:
                  name: bbeth-cfg
                  items:
                    # the bbeth.json in the base is valid but only targets a
                    # single node.
                    - key: bbeth.json
                      path: bbeth.json
        - name: results
          # XXX: frustratingly the emptyDir can not be read by kubectl cp after
          # the job completes. will need to do something else here.
          emptyDir: {}
      containers:
        - name: bbeth
          image: robinbryce/bbeth:main
          imagePullPolicy: Always
          command: ["bbeth", "load", "--config", "/config/bbeth.json"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: results
              mountPath: /results
