apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bbencheth.yaml
configMapGenerator:
  - name: bbencheth-cfg
    files:
      - bbencheth.json
  - name: bbencheth-target-nodes-cfg
    files:
      - static-nodes.json
