# These are the typical secrets for a standard node
# merge with yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' target.yaml thisfile.yaml
# the relative paths are correct for a node dir at <top>/<consensus>/nodes/node{N}
secretGenerator:
- name: ethnodekey-
  files:
    - key
