resources:
# use gethsealedsecrets to generate this file. typically it is generated into
# an environment specific location for the appropriate namespace. Eg
# bbake gethsealedsecrets --destdir k8s/stage/nodes k8s/chain
# resources:
#  - secret-nodekeysealed.yaml
