apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
  - target:
      kind: StatefulSet
      name: ethnode
    path: statefulset-volumes-apisec.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: statefulset-env-security-config.yaml
