patchesJson6902:
  - target:
      kind: Service
      name: ethnode
    path: patch-json-service-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-extip.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-port-containerport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-p2p-port.yaml
