patchesJson6902:
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode1-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode1-extip.yaml
