patchesJson6902:
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode0-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode0-extip.yaml
