---
usage: "make a docker-compose for a geth network from a base.yml and a node.yml"

options:
  networkid:
    default: "53456"
  netrestrict:
    # Use a different CIDR for each consensus type please. just bump the
    # 3rd digit
    default: 172.19.1.10/24
  gastarget:
    usage: sets the --miner.gastarget option for the nodes
    default: "18200000"
  gaslimit:
    usage: sets the --miner.gaslimit option for the nodes
    default: "18200000"
  recommit:
    usage: >
      sets the miner re-commit rate (used to bring in new higher priced
      transactions at regular intervals). defaults high as it can interfere
      with the results as a recommit discards in progress work
    default: 2000s

args:
  configdir:
    usage: >
      The config root directory.
run:
  - task:
      name: configure
      args:
        - ${configdir}
  - command:
      exec: |
        set -e

        TUSKDIR=$(pwd)

        # read the config file fields into BBAKE_ vars.
        CONFIGVARS="${configvars} networkid netrestrict gendoc_wallet raft_blocktime"
        eval ${READ_CONFIG}
        if ${configshow}; then eval ${SHOW_CONFIG}; exit 0; fi
        cd ${launchdir} && cd ${configdir}

        CONFIGDIR=$(pwd)
        RECOMMIT="${recommit}"
        ETHERBASE=${BBAKE_GENDOC_WALLET}
        export ETHERBASE

        source ${BBAKE_PYENV}/bin/activate
        ETHERBASE=$(cat <<PYEND | python3
        import os, sys, pathlib, coincurve, sha3
        if os.environ["ETHERBASE"] or os.environ["ETHERBASE"] == "0x0000000000000000000000000000000000000000":
            sys.exit(-1)
        with open(pathlib.Path(os.environ["BBAKE_NODESDIR"]).joinpath("node0", "key")) as f:
            key = coincurve.PrivateKey.from_hex(f.read())
            pub = key.public_key.format(compressed=False)[1:]
            print("0x" + sha3.keccak_256(pub).digest()[-20:].hex())
        PYEND
        )

        export CONSENSUS_OPTS="\
        --raft --raftport 50000 --raftdnsenable --raftblocktime ${BBAKE_RAFT_BLOCKTIME}"
        export GAS_OPTS="${RECOMMIT:+ --miner.recommit "${RECOMMIT}"} --miner.gastarget ${gastarget} --miner.gaslimit ${gaslimit}"

        cat <<END > .env
        COMPOSE_PROJECT_NAME=${BBAKE_NAME}
        CONSENSUS_OPTS=${CONSENSUS_OPTS}
        NETWORKID=${networkid}
        NETRESTRICT=${netrestrict}
        ETHERBASE=${ETHERBASE}
        QUORUM_SRC=${BBAKE_QUORUM_SRC}
        NODESDIR=${BBAKE_NODESDIR}
        GETH_IMAGE= ${BBAKE_GETH_IMAGE}
        DELVE_IMAGE=${BBAKE_DELVE_IMAGE}
        GAS_OPTS=${GAS_OPTS}
        END
        echo "Wrote .env"

        source ${BBAKE_PYENV}/bin/activate
        cat <<PYEND | python3
        import os, json
        j = None
        with open("bench.json") as f:
            j = json.load(f)
            # The sourcing trick we use doesn't play well with variables that
            # have spaces
            # j["consensus_opts"] = os.environ["CONSENSUS_OPTS"]
            # j["gas_opts"] = os.environ["GAS_OPTS"]
            j["networkid"] = "${networkid}"
            j["netrestrict"] = "${netrestrict}"
        if j is not None:
            with open("bench.json", "w") as f:
                json.dump(j, f, indent=2, sort_keys=True)
        PYEND

        # Merge in the appropriate number of copies of node.yml to the
        # docker-compose.yml we are generating. As we do that add the
        # numeric suffices to each nodes service entry and the working_dir
        # it uses
        cp ${TUSKDIR}/compose/raft/base.yml .
        cp ${TUSKDIR}/compose/raft/node.yml .
        cp base.yml docker-compose.yml

        # each document fragment has to be valid. so they all need the
        # x-node-defaults anchor to be defined.
        cat <<END > tmp.yml
        x-node-defaults:
          &node-defaults
        END

        PORT=8300
        for i in $(seq 0 $((${BBAKE_MAXNODES} - 1)))
        do
            VAL=$i EXPOSED="\"${PORT}:\"" yq eval '
              .node |= .working_dir += env(VAL) |
              del(.x-node-defaults) |
              .node.ports[0] |= . = env(EXPOSED) + . |
              with_entries(.key |= .  + env(VAL))
            ' node.yml
            PORT=$((PORT + 1))
        done >> tmp.yml
        yq eval-all --inplace '
            select(fileIndex == 0) * {"services": select(fileIndex == 1)}
            | del(.services.x-node-defaults)' docker-compose.yml tmp.yml
        echo "Wrote docker-compose.yml"
