apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base/rrr/network
configMapGenerator:
  - name: ethnode-cfg
    behavior: merge
    envs:
    - ./bootnodes.env
    - ./network.env
  - name: genesis
    behavior: merge
    files:
    - ./genesis.json
