nameSuffix: "0"
commonLabels:
  app: ethnode
  app.kubernetes.io/name: ethnode

resources:
  - ./../../../base/raft/node
patchesJson6902:
  # we add the default port this way because it makese it easier to customise.
  # The alternantive - patching a default value in an array entry in yaml via
  # json patch - is very brittle
  - target:
      kind: Service
      name: ethnode
    path: patch-json-statefulset-env-p2p-port.yaml

