nameSuffix: "0"
commonLabels:
  app: ethnode0
  app.kubernetes.io/name: ethnode0
  bootnode: "0"
  bootnode0-extip: "34.105.247.182"
  bootnode0-nodeport: "31210"
  bootnode1-extip: "34.105.247.182"
  bootnode1-nodeport: "31213"
  extip: "34.105.247.182"
  nodeport: "31210"
# These are the typical resources for a standard node
# merge with yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' target.yaml thisfile.yaml
# the relative paths are correct for a node dir at <top>/<consensus>/nodes/node{N}
resources:
  - ./../../node
  # The route file will always be node specific so its in the node{N} dir
  - ingressroute.yaml
# use gethsealedsecrets to generate this file. typically it is generated into
# an environment specific location for the appropriate namespace. Eg
# bbake gethsealedsecrets --destdir k8s/stage/nodes k8s/chain
# resources:
#  - secret-nodekeysealed.yaml

patchesJson6902:
  # we add the default port this way because it makese it easier to customise.
  # The alternantive - patching a default value in an array entry in yaml via
  # json patch - is very brittle
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-p2p-port.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode0-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode0-extip.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode1-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-bootnode1-extip.yaml
  - target:
      kind: Service
      name: ethnode
    path: patch-json-service-nodeport.yaml
  - target:
      kind: Service
      name: ethnode
    path: patch-json-service-nodeport-ports.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-nodeport.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-env-extip.yaml
  - target:
      kind: StatefulSet
      name: ethnode
    path: patch-json-statefulset-port-containerport.yaml
# These are the typical components for a standard node
# merge with yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' target.yaml thisfile.yaml
# the relative paths are correct for a node dir at <top>/<consensus>/nodes/node{N}
components:
  - ./../../../components/volume-config-genesis
  - ./../../../components/apisec
configMapGenerator:
  - name: ethnode-cfg-
    files:
      - plugins.json
      - jwt-auth.json
