name: "Load test one configuration for each consensus alg"
on:
  workflow_dispatch:
jobs:
  raft3:
    uses: robinbryce/blockbench/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "raft"
      numnodes: 3

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  ibft5:
    uses: robinbryce/blockbench/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "ibft"
      numnodes: 5

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}

  rrr5:
    uses: robinbryce/blockbench/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "fetlar-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "rrr"
      numnodes: 5

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_FETLAR }}
