name: "raft, ibft and rrr loadtests"
on:
  workflow_dispatch:
jobs:
  raft3:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "iona-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "raft"
      numnodes: 3
      maxwait: "360"

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_IONA }}

  ibft5:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "iona-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "ibft"
      numnodes: 5
      maxwait: "360"

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_IONA }}

  rrr5:
    uses: robinbryce/benchblock/.github/workflows/loadtest-on-gcp.yaml@main
    with:
      project_id: "iona-1"
      location: "europe-west2-a"
      cluster_name: "kluster"
      consensus: "rrr"
      numnodes: 5
      maxwait: "360"

    secrets:
      gcp_project_key: ${{ secrets.GCP_PROJECT_KEY_IONA }}
