name: release-go-binaries
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release bbeth
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "1.15"
        project_path: "./main/go/bbeth"
        binary_name: "bbeth"
